const app=document.getElementById("app");
const KEY="dunamis_fit_data";
const demoUsers={
  admin:{email:"admin@dunamisfit.com",password:"admin123",name:"Administrador"},
  aluno:{email:"ana@aluno.com",password:"aluno123",name:"Ana"}
};
const seed={students:[
 {id:1,name:"Ana Oliveira",email:"ana@aluno.com",phone:"(00) 99999-0001",plan:"4 dias por semana",value:80,due:10,status:"pending"},
 {id:2,name:"Carlos Silva",email:"carlos@aluno.com",phone:"(00) 99999-0002",plan:"3 dias por semana",value:75,due:15,status:"paid"},
 {id:3,name:"Mariana Souza",email:"mariana@aluno.com",phone:"(00) 99999-0003",plan:"5 dias por semana",value:100,due:5,status:"late"}],
 payments:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||seed;
let current=null; let page="dashboard";
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function login(){app.innerHTML=`<div class="login"><section class="hero"><div class="brand">🏋️ DUNAMIS FIT</div><h1>SUA ACADEMIA,<br><span>NO CONTROLE</span></h1><p>Gerencie alunos, planos, mensalidades e pagamentos em um só lugar.</p></section><section class="login-panel"><div class="card"><h2>ENTRAR</h2><p class="muted">Acesse sua conta para continuar.</p><div class="field"><label>E-mail</label><input id="email" placeholder="voce@email.com"></div><div class="field"><label>Senha</label><input id="pass" type="password" placeholder="Sua senha"></div><button class="btn primary" onclick="doLogin()">Entrar →</button><div class="demo"><button class="btn" onclick="fillDemo('admin')"><strong>🛡 Administrador</strong><span>admin@dunamisfit.com</span></button><button class="btn" onclick="fillDemo('aluno')"><strong>♙ Aluno</strong><span>ana@aluno.com</span></button></div><p class="muted" style="text-align:center;font-size:13px">Senhas de demonstração: admin123 / aluno123</p></div></section></div>`}
function fillDemo(t){document.getElementById("email").value=demoUsers[t].email;document.getElementById("pass").value=demoUsers[t].password}
function doLogin(){const e=document.getElementById("email").value,p=document.getElementById("pass").value;const role=e===demoUsers.admin.email&&p===demoUsers.admin.password?"admin":e===demoUsers.aluno.email&&p===demoUsers.aluno.password?"aluno":null;if(!role)return alert("E-mail ou senha incorretos.");current={...demoUsers[role],role};page=role==="admin"?"dashboard":"meu";render()}
function logout(){current=null;login()}
function nav(p){page=p;render()}
function shell(content){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">🏋️ DUNAMIS FIT</div><nav class="nav">${current.role==="admin"?`<button class="${page==='dashboard'?'active':''}" onclick="nav('dashboard')">📊 Dashboard</button><button class="${page==='students'?'active':''}" onclick="nav('students')">👥 Alunos</button><button class="${page==='payments'?'active':''}" onclick="nav('payments')">💳 Pagamentos</button><button class="${page==='plans'?'active':''}" onclick="nav('plans')">📋 Planos</button><button class="${page==='notifications'?'active':''}" onclick="nav('notifications')">🔔 Notificações</button>`:`<button class="${page==='meu'?'active':''}" onclick="nav('meu')">🏠 Minha mensalidade</button><button class="${page==='history'?'active':''}" onclick="nav('history')">💳 Histórico</button><button class="${page==='notices'?'active':''}" onclick="nav('notices')">🔔 Avisos</button>`}</nav><button class="btn logout" onclick="logout()">Sair</button></aside><main class="main">${content}</main></div>`}
function header(title,sub=""){return `<div class="top"><div><h1>${title}</h1><div class="muted">${sub}</div></div><b>${current.name}</b></div>`}
function render(){if(!current)return login();if(current.role==="aluno")return student();if(page==="students")return students();if(page==="payments")return payments();if(page==="plans")return plans();if(page==="notifications")return notifications();return dashboard()}
function dashboard(){const paid=data.students.filter(s=>s.status==="paid").length,late=data.students.filter(s=>s.status==="late").length,pending=data.students.filter(s=>s.status==="pending").length;return shell(header("Dashboard","Visão geral da Dunamis Fit")+`<div class="grid"><div class="stat"><small>Alunos ativos</small><b>${data.students.length}</b></div><div class="stat"><small>Pagamentos pagos</small><b>${paid}</b></div><div class="stat"><small>Pendentes</small><b>${pending}</b></div><div class="stat"><small>Inadimplentes</small><b>${late}</b></div></div><div class="panel"><h3>Mensalidades</h3>${table(data.students)}</div>`)}
function table(list){return `<table class="table"><thead><tr><th>Aluno</th><th>Plano</th><th>Valor</th><th>Vencimento</th><th>Status</th></tr></thead><tbody>${list.map(s=>`<tr><td><b>${s.name}</b><br><small>${s.email}</small></td><td>${s.plan}</td><td>R$ ${s.value.toFixed(2)}</td><td>Dia ${s.due}</td><td><span class="badge ${s.status}">${s.status==="paid"?"Pago":s.status==="late"?"Atrasado":"Pendente"}</span></td></tr>`).join("")}</tbody></table>`}
function students(){return shell(header("Alunos","Cadastre e gerencie os alunos.")+`<div class="panel"><button class="btn primary" style="width:auto;margin-bottom:18px" onclick="studentForm()">+ Novo aluno</button>${table(data.students)} </div>`)}
function studentForm(id=null){const s=id?data.students.find(x=>x.id===id):{name:"",email:"",phone:"",plan:"4 dias por semana",value:80,due:10,status:"pending"};app.insertAdjacentHTML("beforeend",`<div class="modal"><div class="card"><h3>${id?"Editar":"Novo"} aluno</h3><div class="form-grid"><div class="field"><label>Nome</label><input id="sn" value="${s.name}"></div><div class="field"><label>E-mail</label><input id="se" value="${s.email}"></div><div class="field"><label>Telefone</label><input id="sp" value="${s.phone}"></div><div class="field"><label>Plano</label><select id="spl"><option>3 dias por semana</option><option>4 dias por semana</option><option>5 dias por semana</option></select></div><div class="field"><label>Valor</label><input id="sv" type="number" value="${s.value}"></div><div class="field"><label>Dia de vencimento</label><input id="sd" type="number" value="${s.due}"></div></div><div class="actions"><button class="btn secondary" onclick="render()">Cancelar</button><button class="btn primary" onclick="saveStudent(${id||0})">Salvar</button></div></div></div>`);document.getElementById("spl").value=s.plan}
function saveStudent(id){const s={id:id||Date.now(),name:sn.value,email:se.value,phone:sp.value,plan:spl.value,value:Number(sv.value),due:Number(sd.value),status:"pending"};if(id)data.students=data.students.map(x=>x.id===id?s:x);else data.students.push(s);save();render()}
function payments(){return shell(header("Pagamentos","Registre pagamentos confirmados.")+`<div class="panel"><h3>Controle de pagamentos</h3>${data.students.map(s=>`<div style="display:flex;justify-content:space-between;gap:10px;padding:14px 0;border-bottom:1px solid #eee"><span><b>${s.name}</b><br><small>R$ ${s.value.toFixed(2)} • vencimento dia ${s.due}</small></span><button class="btn ${s.status==='paid'?'secondary':'primary'}" style="width:auto" onclick="pay(${s.id})">${s.status==='paid'?'Pago ✓':'Confirmar pagamento'}</button></div>`).join("")}</div>`)}
function pay(id){const s=data.students.find(x=>x.id===id);s.status="paid";data.payments.push({student:s.name,value:s.value,date:new Date().toLocaleDateString("pt-BR")});save();alert("Pagamento confirmado. O administrador foi atualizado.");render()}
function plans(){return shell(header("Planos","Planos cadastrados para a Dunamis Fit.")+`<div class="grid"><div class="stat"><small>3 dias por semana</small><b>R$ 75</b></div><div class="stat"><small>4 dias por semana</small><b>R$ 80</b></div><div class="stat"><small>5 dias por semana</small><b>R$ 100</b></div></div><div class="panel"><h3>Formas de pagamento</h3><p>Pix • Dinheiro • Cartão</p></div>`)}
function notifications(){return shell(header("Notificações","Regras de aviso da academia.")+`<div class="panel"><div class="notice"><b>3 dias antes:</b> aviso somente dentro do aplicativo.</div><div class="notice"><b>No vencimento:</b> aviso dentro do aplicativo.</div><div class="notice"><b>Após o vencimento:</b> aviso no aplicativo + WhatsApp.</div><div class="notice"><b>Pagamento confirmado:</b> notificação para o administrador.</div><p class="muted">A integração real com WhatsApp será conectada na próxima etapa.</p></div>`)}
function student(){const s=data.students.find(x=>x.email===current.email)||data.students[0];return shell(header("Olá, "+current.name,"Acompanhe sua mensalidade.")+`<div class="panel student-card"><h3>Minha mensalidade</h3><p><b>Plano:</b> ${s.plan}</p><p><b>Valor:</b> R$ ${s.value.toFixed(2)}</p><p><b>Vencimento:</b> dia ${s.due}</p><p><b>Status:</b> <span class="badge ${s.status}">${s.status==="paid"?"Pago":s.status==="late"?"Atrasado":"Pendente"}</span></p>${s.status!=="paid"?`<div class="notice">Lembrete: mantenha sua mensalidade em dia para continuar treinando.</div>`:""}</div>`)}
function history(){const s=data.students.find(x=>x.email===current.email)||data.students[0];return shell(header("Histórico de pagamentos","Seus pagamentos confirmados.")+`<div class="panel">${data.payments.filter(p=>p.student===s.name).length?data.payments.filter(p=>p.student===s.name).map(p=>`<p>R$ ${p.value.toFixed(2)} — ${p.date} <span class="badge paid">Pago</span></p>`).join(""):"<div class='empty'>Nenhum pagamento registrado ainda.</div>"}</div>`)}
function notices(){return shell(header("Avisos","Notificações importantes.")+`<div class="panel"><div class="notice"><b>3 dias antes do vencimento:</b> você receberá um lembrete dentro do aplicativo.</div><div class="notice"><b>Após o vencimento:</b> caso não haja pagamento, sua mensalidade ficará marcada como atrasada e o aviso será reforçado.</div></div>`)}
const oldRender=render; render=function(){if(current?.role==="aluno"&&page==="history")return history();if(current?.role==="aluno"&&page==="notices")return notices();oldRender()}; 
login();
