const app=document.getElementById('app');
const KEY='dunamis_fit_data_v3';
const USERS={admin:{email:'admin@dunamisfit.com',password:'admin123',name:'Administrador'},aluno:{email:'ana@aluno.com',password:'aluno123',name:'Ana'}};
const PLANS={'3 dias por semana':75,'4 dias por semana':80,'5 dias por semana':100};
const seed={students:[
{id:1,name:'Ana Oliveira',birth:'1996-05-10',email:'ana@aluno.com',phone:'(00) 99999-0001',plan:'4 dias por semana',value:80,due:10,start:'2026-01-10',paymentMethod:'Pix',status:'pending',photo:'',evaluations:[{date:'2026-09-07',weight:82.5,height:1.75}]},
{id:2,name:'Carlos Silva',birth:'1992-03-15',email:'carlos@aluno.com',phone:'(00) 99999-0002',plan:'3 dias por semana',value:75,due:15,start:'2026-02-15',paymentMethod:'Dinheiro',status:'paid',photo:'',evaluations:[{date:'2026-09-07',weight:78,height:1.72}]},
{id:3,name:'Mariana Souza',birth:'1998-11-05',email:'mariana@aluno.com',phone:'(00) 99999-0003',plan:'5 dias por semana',value:100,due:5,start:'2026-03-05',paymentMethod:'Cartão',status:'late',photo:'',evaluations:[{date:'2026-09-07',weight:68,height:1.65}]}
],payments:[],notifications:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
let current=null,page='dashboard';
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(v){return Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2})}
function dateNow(){return new Date().toISOString().slice(0,10)}
function fmtDate(v){if(!v)return '—';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function age(b){if(!b)return '—';const d=new Date(b+'T00:00:00'),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a}
function bmi(w,h){return w&&h?w/(h*h):0}
function bmiLabel(v){return !v?'—':v<18.5?'Abaixo do peso':v<25?'Faixa adequada':v<30?'Sobrepeso':'Obesidade'}
function last(s){return s?.evaluations?.length?s.evaluations[s.evaluations.length-1]:null}
function statusText(s){return s==='paid'?'Pago':s==='late'?'Inadimplente':'Pendente'}
function statusClass(s){return s||'pending'}
function currentStatus(s){if(s.status==='paid')return 'paid';const now=new Date(),due=new Date(now.getFullYear(),now.getMonth(),Number(s.due));return now>due?'late':'pending'}
function syncStatuses(){data.students.forEach(s=>{if(s.status!=='paid')s.status=currentStatus(s)});save()}
syncStatuses();
function avatar(s,size='56px'){return s.photo?`<img class="avatar" style="width:${size};height:${size}" src="${s.photo}" alt="Foto de ${s.name}">`:`<div class="avatar avatar-fallback" style="width:${size};height:${size}">${(s.name||'?').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div>`}
function login(){app.innerHTML=`<div class="login"><section class="hero" style="padding:0;position:relative;overflow:hidden;background:#000;justify-content:center;align-items:center"><img src="dunamis-fit-abertura.png" alt="Dunamis Fit - Força que vem do alto" style="width:100%;height:100%;object-fit:cover;display:block"></section><section class="login-panel"><div class="card"><h2>ENTRAR</h2><p class="muted">Acesse sua conta para continuar.</p><div class="field"><label>E-mail</label><input id="email" placeholder="voce@email.com"></div><div class="field"><label>Senha</label><input id="pass" type="password" placeholder="Sua senha" onkeydown="if(event.key==='Enter')doLogin()"></div><button class="btn primary" onclick="doLogin()">Entrar →</button><div class="demo"><button class="btn" onclick="fill('admin')"><strong>🛡 Administrador</strong><span>admin@dunamisfit.com</span></button><button class="btn" onclick="fill('aluno')"><strong>♙ Aluno</strong><span>ana@aluno.com</span></button></div><p class="muted" style="text-align:center;font-size:13px">Senhas de demonstração: admin123 / aluno123</p></div></section></div>`}
function fill(t){email.value=USERS[t].email;pass.value=USERS[t].password}
function doLogin(){const e=email.value.trim(),p=pass.value;let role=Object.keys(USERS).find(k=>USERS[k].email===e&&USERS[k].password===p);if(!role)return alert('E-mail ou senha incorretos.');current={...USERS[role],role};page=role==='admin'?'dashboard':'meu';render()}
function logout(){current=null;login()}
function nav(p){page=p;render()}
function shell(content){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">🏋️ DUNAMIS FIT</div>${current.role==='aluno'?`<div class="user-mini">${avatar(data.students.find(s=>s.email===current.email)||{},44)}<div><b>${current.name}</b><small>Área do aluno</small></div></div>`:''}<nav class="nav">${current.role==='admin'?`<button class="${page==='dashboard'?'active':''}" onclick="nav('dashboard')">📊 Dashboard</button><button class="${page==='students'?'active':''}" onclick="nav('students')">👥 Alunos</button><button class="${page==='payments'?'active':''}" onclick="nav('payments')">💳 Pagamentos</button><button class="${page==='plans'?'active':''}" onclick="nav('plans')">📋 Planos</button><button class="${page==='notifications'?'active':''}" onclick="nav('notifications')">🔔 Notificações</button>`:`<button class="${page==='meu'?'active':''}" onclick="nav('meu')">🏠 Minha mensalidade</button><button class="${page==='development'?'active':''}" onclick="nav('development')">📈 Meu desenvolvimento</button><button class="${page==='history'?'active':''}" onclick="nav('history')">💳 Histórico</button><button class="${page==='notices'?'active':''}" onclick="nav('notices')">🔔 Avisos</button><button class="${page==='profile'?'active':''}" onclick="nav('profile')">👤 Meu perfil</button>`}</nav><button class="btn logout" onclick="logout()">Sair</button></aside><main class="main">${content}</main></div>`}
function header(title,sub=''){return `<div class="top"><div><h1>${title}</h1><div class="muted">${sub}</div></div><b>${current.name}</b></div>`}
function table(list){return `<div class="table-wrap"><table class="table"><thead><tr><th>Aluno</th><th>Plano</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr></thead><tbody>${list.map(s=>`<tr><td><div class="person">${avatar(s,42)}<div><b>${s.name}</b><br><small>${s.email}</small></div></div></td><td>${s.plan}</td><td>R$ ${money(s.value)}</td><td>Dia ${s.due}</td><td><span class="badge ${statusClass(s.status)}">${statusText(s.status)}</span></td><td><div class="actions"><button class="btn secondary" onclick="studentForm(${s.id})">Editar</button><button class="btn secondary" onclick="evaluationForm(${s.id})">Avaliar</button></div></td></tr>`).join('')}</tbody></table></div>`}
function dashboard(){const paid=data.students.filter(s=>s.status==='paid'),late=data.students.filter(s=>s.status==='late'),pending=data.students.filter(s=>s.status==='pending'),total=data.students.reduce((a,s)=>a+s.value,0),received=paid.reduce((a,s)=>a+s.value,0),rate=data.students.length?Math.round(paid.length/data.students.length*100):0;return shell(header('Dashboard','Visão geral da Dunamis Fit')+`<div class="grid"><div class="stat"><small>👥 Alunos ativos</small><b>${data.students.length}</b><small>Base cadastrada</small></div><div class="stat"><small>💰 Receita prevista</small><b>R$ ${money(total)}</b><small>Mensalidades atuais</small></div><div class="stat"><small>✅ Pagamentos pagos</small><b>${paid.length}</b><small>${rate}% da base</small></div><div class="stat"><small>🔴 Inadimplentes</small><b>${late.length}</b><small>${pending.length} pendente(s)</small></div></div><div class="dashboard-grid"><div class="panel"><h3>Resumo financeiro</h3><span class="muted">Situação das mensalidades</span><div class="progress"><span style="width:${rate}%"></span></div><div class="metric-row"><span>Recebido</span><strong>R$ ${money(received)}</strong></div><div class="metric-row"><span>A receber</span><strong>R$ ${money(total-received)}</strong></div><div class="metric-row"><span>Inadimplentes</span><strong>${late.length}</strong></div></div><div class="panel"><h3>Automação de cobrança</h3><p class="muted">O sistema acompanha vencimentos e organiza os avisos automaticamente.</p><div class="notice success">✓ Lembrete interno: 3 dias antes do vencimento</div><div class="notice danger">! Inadimplência: aviso no app e WhatsApp quando a integração estiver conectada</div></div></div><div class="panel"><div class="panel-head"><div><h3>Alunos em destaque</h3><span class="muted">Resumo cadastral</span></div><button class="btn secondary small-btn" onclick="nav('students')">Ver todos</button></div>${table(data.students.slice(0,5))}</div>`)}
function students(){return shell(header('Alunos','Cadastre, edite e acompanhe os alunos.')+`<div class="panel"><button class="btn primary small-btn" onclick="studentForm()">+ Novo aluno</button>${table(data.students)}</div>`)}
function studentForm(id){const s=id?data.students.find(x=>x.id===id):{name:'',birth:'',email:'',phone:'',plan:'4 dias por semana',value:80,due:10,start:dateNow(),paymentMethod:'Pix',status:'pending',evaluations:[],photo:''};app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="card modal-card"><h3>${id?'Editar':'Novo'} aluno</h3><div class="form-grid"><div class="field"><label>Nome completo</label><input id="sn" value="${s.name}"></div><div class="field"><label>Data de nascimento</label><input id="sb" type="date" value="${s.birth||''}"></div><div class="field"><label>E-mail</label><input id="se" value="${s.email}"></div><div class="field"><label>WhatsApp</label><input id="sp" value="${s.phone||''}"></div><div class="field"><label>Plano</label><select id="spl" onchange="sv.value=PLANS[this.value]"><option>3 dias por semana</option><option>4 dias por semana</option><option>5 dias por semana</option></select></div><div class="field"><label>Valor</label><input id="sv" type="number" step="0.01" value="${s.value}"></div><div class="field"><label>Dia de vencimento</label><input id="sd" type="number" min="1" max="31" value="${s.due}"></div><div class="field"><label>Data de início</label><input id="sst" type="date" value="${s.start||''}"></div><div class="field"><label>Forma de pagamento</label><select id="spm"><option>Pix</option><option>Dinheiro</option><option>Cartão</option></select></div><div class="field"><label>Peso atual (kg)</label><input id="sw" type="number" step="0.1" value="${last(s)?.weight||''}"></div><div class="field"><label>Altura (m)</label><input id="sh" type="number" step="0.01" value="${last(s)?.height||''}"></div></div><div class="actions"><button class="btn secondary" onclick="render()">Cancelar</button><button class="btn primary" onclick="saveStudent(${id||0})">Salvar</button></div></div></div>`);spl.value=s.plan;spm.value=s.paymentMethod||'Pix'}
function saveStudent(id){const old=id?data.students.find(x=>x.id===id):null;const w=Number(sw.value),h=Number(sh.value);let evaluations=old?.evaluations||[];if(w&&h)evaluations=[...evaluations,{date:dateNow(),weight:w,height:h}];const s={id:id||Date.now(),name:sn.value.trim(),birth:sb.value,email:se.value.trim(),phone:sp.value.trim(),plan:spl.value,value:Number(sv.value)||PLANS[spl.value],due:Number(sd.value),start:sst.value,paymentMethod:spm.value,status:old?.status||'pending',photo:old?.photo||'',evaluations};if(!s.name||!s.email)return alert('Informe nome e e-mail.');if(id)data.students=data.students.map(x=>x.id===id?s:x);else data.students.push(s);save();render()}
function evaluationForm(id){const s=data.students.find(x=>x.id===id);app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="card modal-card"><h3>Nova avaliação — ${s.name}</h3><div class="form-grid"><div class="field"><label>Data</label><input id="ed" type="date" value="${dateNow()}"></div><div class="field"><label>Peso (kg)</label><input id="ew" type="number" step="0.1"></div><div class="field"><label>Altura (m)</label><input id="eh" type="number" step="0.01" value="${last(s)?.height||''}"></div></div><p class="muted">IMC, TMB e GET serão calculados automaticamente.</p><div class="actions"><button class="btn secondary" onclick="render()">Cancelar</button><button class="btn primary" onclick="saveEvaluation(${id})">Salvar avaliação</button></div></div></div>`)}
function saveEvaluation(id){const s=data.students.find(x=>x.id===id),w=Number(ew.value),h=Number(eh.value);if(!w||!h)return alert('Informe peso e altura.');s.evaluations.push({date:ed.value,weight:w,height:h});save();render()}
function payments(){return shell(header('Pagamentos','Controle financeiro e confirmação de mensalidades.')+`<div class="panel"><div class="panel-head"><div><h3>Mensalidades</h3><span class="muted">Pagamentos em dinheiro podem ser confirmados manualmente. Pix/cartão serão automatizados quando o gateway for conectado.</span></div></div>${data.students.map(s=>`<div class="payment-row"><div class="person">${avatar(s,46)}<div><b>${s.name}</b><small>R$ ${money(s.value)} • vence dia ${s.due} • ${s.paymentMethod}</small></div></div><div><span class="badge ${statusClass(s.status)}">${statusText(s.status)}</span><button class="btn ${s.status==='paid'?'secondary':'primary'} small-btn" onclick="pay(${s.id})">${s.status==='paid'?'Pago ✓':'Confirmar pagamento'}</button></div></div>`).join('')}</div>`)}
function pay(id){const s=data.students.find(x=>x.id===id);s.status='paid';data.payments.unshift({id:Date.now(),studentId:id,student:s.name,value:s.value,date:dateNow(),method:s.paymentMethod});data.notifications.unshift({date:dateNow(),text:`Pagamento confirmado: ${s.name} — R$ ${money(s.value)}`});save();alert('Pagamento confirmado. O administrador foi atualizado.');render()}
function plans(){return shell(header('Planos','Planos e valores da Dunamis Fit.')+`<div class="plans-grid">${Object.entries(PLANS).map(([p,v],i)=>`<div class="plan-card"><span class="plan-tag">PLANO ${i+1}</span><h3>${p}</h3><strong>R$ ${money(v)}</strong><p>Treinos por semana</p><button class="btn secondary" onclick="nav('students')">Ver alunos</button></div>`).join('')}</div>`)}
function notifications(){return shell(header('Notificações','Central de avisos do administrador.')+`<div class="panel">${data.notifications.length?data.notifications.map(n=>`<div class="notice success">✓ ${n.text}<small>${fmtDate(n.date)}</small></div>`).join(''):`<div class="empty">Nenhuma notificação ainda.</div>`}<div class="notice">ℹ O fluxo de WhatsApp ficará pronto na etapa de integração com o provedor.</div></div>`)}
function getStudent(){return data.students.find(s=>s.email===current.email)||data.students[0]}
function billingCard(s){const st=s.status==='paid'?'paid':currentStatus(s);return `<div class="billing-card"><div class="billing-main"><span>Mensalidade</span><strong>R$ ${money(s.value)}</strong><span>${s.plan} • ${s.paymentMethod}</span></div><div><span class="badge ${st}">${statusText(st)}</span><p class="muted">Vencimento: dia ${s.due}</p></div></div>`}
function alunoHome(){const s=getStudent(),e=last(s),v=bmi(e?.weight,e?.height);return shell(header(`Olá, ${s.name.split(' ')[0]} 👋`,'Seu resumo na Dunamis Fit')+`<div class="profile-hero"><div>${avatar(s,82)}<div><h2>${s.name}</h2><span class="muted">${age(s.birth)} anos • ${s.plan}</span></div></div><button class="btn secondary small-btn" onclick="nav('profile')">Editar perfil</button></div>${billingCard(s)}<div class="grid"><div class="stat"><small>⚖ Peso atual</small><b>${e?.weight||'—'} kg</b><small>Última avaliação</small></div><div class="stat"><small>📏 Altura</small><b>${e?.height||'—'} m</b><small>Cadastro</small></div><div class="stat"><small>📐 IMC</small><b>${v?v.toFixed(1):'—'}</b><small>${bmiLabel(v)}</small></div><div class="stat"><small>🔥 GET estimado</small><b>${getValue(s)||'—'} kcal</b><small>Gasto diário estimado</small></div></div><div class="panel"><h3>Seus próximos passos</h3><div class="quick-actions"><button class="btn primary" onclick="nav('development')">Ver desenvolvimento</button><button class="btn secondary" onclick="nav('history')">Ver pagamentos</button><button class="btn secondary" onclick="nav('profile')">Minha foto e dados</button></div></div>`)}
function tmbValue(s){const e=last(s);if(!e?.weight||!e?.height||!s.birth)return 0;const a=age(s.birth);return Math.round(10*e.weight+6.25*(e.height*100)-5*a+5)}
function getValue(s){const t=tmbValue(s);return t?Math.round(t*1.375):0}
function development(){const s=getStudent(),e=last(s),v=bmi(e?.weight,e?.height),t=tmbValue(s),g=getValue(s);return shell(header('Meu desenvolvimento','Acompanhe sua evolução física.')+`<div class="development-head"><div>${avatar(s,72)}<div><h2>${s.name}</h2><span class="muted">Histórico de avaliações</span></div></div></div><div class="grid"><div class="stat"><small>⚖ Peso</small><b>${e?.weight||'—'} kg</b></div><div class="stat"><small>📐 IMC</small><b>${v?v.toFixed(1):'—'}</b><small>${bmiLabel(v)}</small></div><div class="stat"><small>🔥 TMB</small><b>${t||'—'} kcal</b><small>Taxa metabólica basal</small></div><div class="stat"><small>⚡ GET</small><b>${g||'—'} kcal</b><small>Gasto energético total estimado</small></div></div><div class="panel"><h3>Histórico de avaliações</h3><div class="timeline">${(s.evaluations||[]).slice().reverse().map(x=>`<div class="timeline-item"><b>${fmtDate(x.date)}</b><span>${x.weight} kg • ${x.height} m • IMC ${bmi(x.weight,x.height).toFixed(1)}</span></div>`).join('')||'<div class="empty">Nenhuma avaliação registrada.</div>'}</div></div>`)}
function history(){const s=getStudent(),items=data.payments.filter(p=>p.studentId===s.id);return shell(header('Histórico','Seus pagamentos confirmados.')+`<div class="panel"><h3>Histórico financeiro</h3>${items.length?items.map(p=>`<div class="payment-row"><div><b>${fmtDate(p.date)}</b><small>${p.method}</small></div><strong>R$ ${money(p.value)}</strong><span class="badge paid">Pago</span></div>`).join(''):'<div class="empty">Ainda não há pagamentos registrados.</div>'}</div>`)}
function notices(){const s=getStudent(),st=s.status==='paid'?'paid':currentStatus(s);let msg=st==='late'?'<div class="notice danger">⚠ Sua mensalidade está em atraso. Regularize o pagamento para manter seu cadastro em dia.</div>':st==='pending'?'<div class="notice">🔔 Sua mensalidade está próxima do vencimento. Consulte a data no seu painel.</div>':'<div class="notice success">✓ Sua mensalidade está registrada como paga.</div>';return shell(header('Avisos','Informações importantes sobre sua mensalidade.')+`<div class="panel">${msg}<div class="notice">📅 O lembrete interno é programado para aparecer 3 dias antes do vencimento.</div><div class="notice danger">WhatsApp: será enviado automaticamente após a integração com o provedor de mensagens.</div></div>`)}
function profile(){const s=getStudent();return shell(header('Meu perfil','Mantenha seus dados atualizados.')+`<div class="panel profile-panel"><div class="profile-photo">${avatar(s,120)}<div><h2>${s.name}</h2><span class="muted">Foto de perfil</span><input id="photoInput" type="file" accept="image/*" onchange="changePhoto(event)"></div></div><div class="form-grid"><div class="field"><label>Nome</label><input value="${s.name}" readonly></div><div class="field"><label>Data de nascimento</label><input value="${fmtDate(s.birth)}" readonly></div><div class="field"><label>E-mail</label><input value="${s.email}" readonly></div><div class="field"><label>WhatsApp</label><input value="${s.phone||'—'}" readonly></div></div></div>`)}
function changePhoto(ev){const file=ev.target.files?.[0];if(!file)return;if(file.size>1200000)return alert('Escolha uma foto de até 1,2 MB.');const r=new FileReader();r.onload=()=>{const s=getStudent();s.photo=r.result;save();render()};r.readAsDataURL(file)}
function render(){if(!current)return login();syncStatuses();if(current.role==='admin'){if(page==='students')return students();if(page==='payments')return payments();if(page==='plans')return plans();if(page==='notifications')return notifications();return dashboard()}if(page==='development')return development();if(page==='history')return history();if(page==='notices')return notices();if(page==='profile')return profile();return alunoHome()}
render();