// Dunamis Fit — evolução física e avaliações: camada independente do login.
(function(){
  'use strict';
  const sb=window.dunamisSupabase;
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const num=v=>Number(v||0);
  const fmt=n=>Number(n).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1});
  const today=()=>new Date().toISOString().slice(0,10);
  const evals=s=>(s?.evaluations||[]).filter(e=>num(e.weight)>0&&num(e.height)>0).sort((a,b)=>String(a.date).localeCompare(String(b.date)));
  const bmi=(w,h)=>w>0&&h>0?w/(h*h):0;
  const bmiText=v=>!v?'—':v<18.5?'Abaixo do peso':v<25?'Faixa adequada':v<30?'Sobrepeso':'Obesidade';
  const activity={sedentario:['Sedentário',1.2],leve:['Levemente ativo',1.375],moderado:['Moderadamente ativo',1.55],alto:['Muito ativo',1.725],atleta:['Extremamente ativo',1.9]};
  function ageAt(birth,date){if(!birth)return 0;const b=new Date(birth+'T00:00:00'),d=new Date(date+'T00:00:00');let a=d.getFullYear()-b.getFullYear();if(d.getMonth()<b.getMonth()||(d.getMonth()===b.getMonth()&&d.getDate()<b.getDate()))a--;return a}
  function tmb(s,e,sex){const a=ageAt(s.birth,e.date),w=num(e.weight),h=num(e.height);if(!a||!w||!h||!sex)return 0;return sex==='female'?(10*w+6.25*h*100-5*a-161):(10*w+6.25*h*100-5*a+5)}
  function metricCards(s,e){const b=bmi(num(e?.weight),num(e?.height));const previous=evals(s).slice(-2,-1)[0];const delta=previous?num(e.weight)-num(previous.weight):0;return `<div class="grid"><div class="stat"><small>⚖️ Peso atual</small><b>${fmt(e?.weight||0)} kg</b><small>${delta?`${delta>0?'+':''}${fmt(delta)} kg desde a avaliação anterior`:'Primeira avaliação registrada'}</small></div><div class="stat"><small>📏 Altura</small><b>${fmt(e?.height||0)} m</b><small>Última avaliação</small></div><div class="stat"><small>📊 IMC</small><b>${b?b.toFixed(1):'—'}</b><small>${bmiText(b)}</small></div><div class="stat"><small>📅 Avaliação</small><b>${e?.date?fmtDate(e.date):'—'}</b><small>Dados mais recentes</small></div></div>`}
  function chart(s){const list=evals(s);if(list.length<2)return `<div class="panel"><h3>Evolução do peso</h3><p class="muted">Registre pelo menos duas avaliações para visualizar a evolução.</p></div>`;const vals=list.map(e=>num(e.weight));const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1);const w=760,h=230,p=34;const pts=list.map((e,i)=>{const x=p+(i*(w-2*p)/Math.max(list.length-1,1));const y=h-p-((num(e.weight)-min)/range)*(h-2*p);return [x,y,e]});const poly=pts.map(x=>`${x[0].toFixed(1)},${x[1].toFixed(1)}`).join(' ');return `<div class="panel"><div class="panel-head"><div><h3>Evolução do peso</h3><span class="muted">${fmt(vals[0])} kg → ${fmt(vals[vals.length-1])} kg</span></div><strong>${fmt(vals[vals.length-1]-vals[0])} kg</strong></div><div style="overflow:auto"><svg viewBox="0 0 ${w} ${h}" width="100%" height="230" role="img" aria-label="Gráfico de evolução do peso"><polyline points="${poly}" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${pts.map(([x,y,e])=>`<circle cx="${x}" cy="${y}" r="5" fill="currentColor"><title>${fmt(e.weight)} kg — ${fmtDate(e.date)}</title></circle>`).join('')} </svg></div></div>`}
  function loadMetabolic(s){if(!sb||!s?.id)return;sb.from('evaluations').select('evaluation_date,weight,height,sex,activity_level').eq('student_id',s.id).order('evaluation_date',{ascending:false}).limit(1).maybeSingle().then(({data:e,error})=>{const el=document.getElementById('metabolic-panel');if(!el||error)return;if(!e){el.innerHTML='<div class="panel"><h3>Energia diária</h3><p class="muted">Ainda não há dados suficientes para estimar TMB e GET.</p></div>';return}const b=bmi(num(e.weight),num(e.height));const t=tmb(s,{...e,date:e.evaluation_date},e.sex);const g=t&&e.activity_level?Math.round(t*activity[e.activity_level][1]):0;el.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>Energia diária estimada</h3><span class="muted">Baseada na avaliação de ${fmtDate(e.evaluation_date)}.</span></div></div><div class="grid"><div class="stat"><small>🔥 TMB</small><b>${t?Math.round(t)+' kcal/dia':'—'}</b><small>${t?'Mifflin-St Jeor':'Sexo não informado'}</small></div><div class="stat"><small>⚡ GET</small><b>${g?g+' kcal/dia':'—'}</b><small>${g?activity[e.activity_level][0]:'Atividade não informada'}</small></div><div class="stat"><small>📊 IMC</small><b>${b?b.toFixed(1):'—'}</b><small>${bmiText(b)}</small></div></div><p class="muted" style="margin-top:12px">TMB e GET são estimativas e não substituem avaliação profissional individualizada.</p></div>`})}
  window.development=function(){if(!current)return;const s=current.role==='aluno'?(data.students||[]).find(x=>String(x.id)===String(current.studentId)||x.email===current.email):(data.students||[])[0];if(!s)return shell(header('Meu desenvolvimento','Acompanhe sua evolução física.')+`<div class="panel"><p class="muted">Nenhum aluno encontrado.</p></div>`);const list=evals(s),e=list[list.length-1];const html=shell(header(current.role==='aluno'?'Meu desenvolvimento':'Desenvolvimento','Avaliações físicas e evolução.')+metricCards(s,e)+`<div id="metabolic-panel"><div class="panel"><h3>Energia diária estimada</h3><p class="muted">Calculando dados da avaliação mais recente…</p></div></div>`+chart(s)+`<div class="panel"><div class="panel-head"><div><h3>Histórico de avaliações</h3><span class="muted">Ordenado da mais antiga para a mais recente.</span></div>${current.role==='admin'?`<button class="btn primary small-btn" onclick="evaluationForm(${esc(s.id)})">+ Nova avaliação</button>`:''}</div>${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Peso</th><th>Altura</th><th>IMC</th><th>Classificação</th></tr></thead><tbody>${list.slice().reverse().map(x=>{const b=bmi(num(x.weight),num(x.height));return `<tr><td>${fmtDate(x.date)}</td><td>${fmt(x.weight)} kg</td><td>${fmt(x.height)} m</td><td>${b.toFixed(1)}</td><td>${bmiText(b)}</td></tr>`}).join('')}</tbody></table></div>`:`<p class="muted">Ainda não há avaliações registradas.</p>`}</div>`);setTimeout(()=>loadMetabolic(s),0);return html};
  window.history=function(){if(!current)return;const s=(data.students||[]).find(x=>String(x.id)===String(current.studentId)||x.email===current.email);const rows=(data.payments||[]).filter(p=>String(p.studentId||p.student_id)===String(s?.id)).sort((a,b)=>String(b.dueDate||b.due_date||'').localeCompare(String(a.dueDate||a.due_date||'')));return shell(header('Histórico financeiro','Consulte suas mensalidades e pagamentos.')+`<div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Vencimento</th><th>Valor</th><th>Forma</th><th>Status</th><th>Pagamento</th></tr></thead><tbody>${rows.length?rows.map(p=>`<tr><td>${fmtDate(p.dueDate||p.due_date)}</td><td>R$ ${Number(p.amount||p.value||0).toLocaleString('pt-BR',{minimumFractionDigits:2})}</td><td>${esc(p.method||'—')}</td><td><span class="badge ${esc(p.status||'pending')}">${statusText(p.status||'pending')}</span></td><td>${fmtDate(p.paidAt||p.paid_at||'')}</td></tr>`).join(''):`<tr><td colspan="5">Nenhum pagamento registrado.</td></tr>`}</tbody></table></div></div>`)};
  const originalEvaluationForm=window.evaluationForm;
  window.evaluationForm=function(id){const s=(data.students||[]).find(x=>String(x.id)===String(id));if(!s)return;const e=last(s)||{};app.insertAdjacentHTML('beforeend',`<div class="modal"><div class="card modal-card"><h3>Nova avaliação — ${esc(s.name)}</h3><div class="form-grid"><div class="field"><label>Data</label><input id="ed" type="date" value="${today()}"></div><div class="field"><label>Peso (kg)</label><input id="ew" type="number" min="1" max="500" step="0.1" value="${e.weight||''}" oninput="devPreview()"></div><div class="field"><label>Altura (m)</label><input id="eh" type="number" min="0.5" max="2.5" step="0.01" value="${e.height||''}" oninput="devPreview()"></div><div class="field"><label>Sexo para TMB <small>(opcional)</small></label><select id="esex" onchange="devPreview()"><option value="">Não informado</option><option value="female">Feminino</option><option value="male">Masculino</option></select></div><div class="field"><label>Nível de atividade <small>(opcional)</small></label><select id="eact" onchange="devPreview()"><option value="">Não informado</option><option value="sedentario">Sedentário</option><option value="leve">Levemente ativo</option><option value="moderado">Moderadamente ativo</option><option value="alto">Muito ativo</option><option value="atleta">Extremamente ativo</option></select></div></div><div id="dev-preview" class="notice success">Informe peso e altura para visualizar o IMC.</div><p class="muted">TMB/GET só serão exibidos quando sexo e nível de atividade forem informados. A estimativa usa Mifflin-St Jeor e fator de atividade.</p><div class="actions"><button class="btn secondary" onclick="render()">Cancelar</button><button class="btn primary" onclick="saveEvaluation(${esc(id)})">Salvar avaliação</button></div></div></div>`);devPreview()};
  window.devPreview=function(){const s=(data.students||[]).find(x=>String(x.id)===String(current?.studentId||'')||x.email===current?.email)||{};const w=num(document.getElementById('ew')?.value),h=num(document.getElementById('eh')?.value),b=bmi(w,h),sex=document.getElementById('esex')?.value,act=document.getElementById('eact')?.value;let text=b?`IMC ${b.toFixed(1)} — ${bmiText(b)}.`:'Informe peso e altura para visualizar o IMC.';if(sex&&act){const t=tmb(s,{weight:w,height:h,date:document.getElementById('ed')?.value||today()},sex),g=t*activity[act][1];text+=` TMB estimada: ${Math.round(t)} kcal/dia. GET estimado: ${Math.round(g)} kcal/dia.`}else text+=' TMB/GET: informe sexo e atividade para estimar.';const el=document.getElementById('dev-preview');if(el)el.textContent=text};
  window.saveEvaluation=async function(id){if(!current||current.role!=='admin')return alert('Somente o administrador pode registrar avaliações.');const s=(data.students||[]).find(x=>String(x.id)===String(id)),w=num(document.getElementById('ew')?.value),h=num(document.getElementById('eh')?.value),d=document.getElementById('ed')?.value||today(),sex=document.getElementById('esex')?.value||null,act=document.getElementById('eact')?.value||null;if(!w||!h||w<1||h<0.5)return alert('Informe peso e altura válidos.');if(!sb)return alert('Banco de dados indisponível.');const q=await sb.from('evaluations').select('id,weight,height,evaluation_date,sex,activity_level').eq('student_id',id).eq('evaluation_date',d).limit(1);if(q.error)return alert('Não foi possível consultar a avaliação.');const duplicate=(q.data||[]).find(x=>num(x.weight)===w&&num(x.height)===h);if(duplicate)return alert('Essa avaliação já está registrada.');const ins=await sb.from('evaluations').insert({student_id:id,evaluation_date:d,weight:w,height:h,sex,activity_level:act});if(ins.error)return alert('Não foi possível salvar a avaliação: '+ins.error.message);if(typeof refreshCloudData==='function')await refreshCloudData();render()};
  if(originalEvaluationForm&&typeof originalEvaluationForm==='function')window._originalEvaluationForm=originalEvaluationForm;
})();
